server:
  port: 8085
spring:
  application:
    name: coupon-service
  cloud:
    nacos:
      server-addr: 123.60.183.42:8848 # nacos地址
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hm.db.host}:3307/hm-coupon?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}
  redis:
    host: ${hm.redis.host:localhost}
    port: 6379
    password: ${hm.redis.pw:}
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms

# RocketMQ 配置
rocketmq:
  name-server: ${hm.mq.host:localhost}:9876  # RocketMQ NameServer 地址
  producer:
    group: coupon-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
  consumer:
    group: coupon-consumer-group

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

knife4j:
  enable: true
  openapi:
    title: 黑马商城优惠券接口文档
    description: "黑马商城优惠券秒杀接口文档"
    email: zhanghuyi@itcast.cn
    concat: binZhang
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.coupon.controller

