hmall:
  db:
    host: 127.0.0.1
    port: 3306
    database: hm-behavior
    un: root
    pw: 123
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123321
  nacos:
    host: 127.0.0.1
    port: 8848
  xxljob:
    host: 127.0.0.1
    port: 8880

